<?php
///////////////////////////////////////////////////////////////////
//////////////////////// Menu Generator V 1.0  ////////////////////
//                                                               //
//  Copyright 2015 by Dhruv Gramopadhye. All Rights Reserved.    //
//  Do not copy in any form without an explicit written permit   //
//  allowing you to do so from Dhruv Gramopadhye                 //
///////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////
?>
<html>
	<head>
		<title>Order Complete</title>
		<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<script>
		console.log("///////////////////////////////////////////////////////////////////\n//////////////////////// Menu Generator V 1.0  ///////////////////\n///                                                               //\n//  Copyright 2015 by Dhruv Gramopadhye. All Rights Reserved.    //\n//  Do not copy in any form without an explicit written permit   //\n//  allowing you to do so from Dhruv Gramopadhye                 //\n// ///////////////////////////////////////////////////////////// //\n//////////////////////////////////////////////////////////////////");
		</script>
	</head>
	<body>
<div class="jumbotron">
  <h1><?php echo $_GET["title"] ?></h1>      
</div>
	<div class="container">
				<?php 
	$file = fopen($_GET["studentid"]. ".txt", "w");
	fwrite($_GET["studentid"]. ".txt", $_POST);
    fclose($file);
?>
		<br/>You ave finished ordering.
		</div>	<script>console.log("Post Data: <?php echo $_POST ?>     Get Data: <?php echo $_GET ?>")</script>
		<div class="jumbotron">
			<small>Generated by Dhruv Gramopadhye's MenuGen</small>
		</div>
</body>
</html>
